#! /bin/sh
# Copyright 2023 - 2024, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=SC2164
cd "${MESONCURRENTCONFIGDIR}"
echo "Build standard release build"
rm -rf _build-w-o-warnings
meson setup _build-w-o-warnings -Dxwayland=true -Dman-pages=true --buildtype=release --fatal-meson-warnings || RESULT=1
ninja -C _build-w-o-warnings || RESULT=1
rm -rf _build-w-o-warnings

exit "${RESULT}"
