#! /bin/sh
# Copyright 2023, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}"
echo "Build without xwayland"
rm -rf _build-w-o-xwayland
meson setup _build-w-o-xwayland -Dxwayland=false -Dman-pages=false --buildtype=release --fatal-meson-warnings || RESULT=1
ninja -C _build-w-o-xwayland || RESULT=1
rm -rf _build-w-o-xwayland

exit "${RESULT}"
