#!/bin/bash
# Copyright 2023, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}"

# Check that no TODO statements remain in the release directory
if ! grep -Rq "TODO" .
then
	echo "[x] TODO"
else
	RESULT=1
	echo "[ ] TODO"
fi

# Check that Cagebreak does not falsely claim to be POSIX compliant
if ! grep -Rq "_POSIX_C_SOURCE" .
then
	echo "[x] _POSIX_C_SOURCE"
else
	RESULT=1
	echo "[ ] _POSIX_C_SOURCE"
fi


exit "${RESULT}"
