#!/bin/bash
# Copyright 2023 - 2025, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}"

# Check that no TODO statements remain in the release directory
if grep --exclude='test/illegal-strings' --exclude-dir='build' --exclude-dir='test' --exclude-dir='fuzz_corpus' -Rn "TODO" ./**
then
	echo "[x] TODO"
else
	RESULT=1
	echo "[ ] TODO"
fi

exit "${RESULT}"
