#!/bin/bash
# Copyright 2023 - 2024, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}"
rm -rf _build-scan-build
meson setup _build-scan-build -Dxwayland=true -Dman-pages=true --buildtype=release || RESULT=1
SCANBUILD="$(pwd)/test/testing-configurations/my-scan-build" ninja -C _build-scan-build scan-build || RESULT=1
rm -rf _build-scan-build

exit "${RESULT}"
