#!/bin/bash
# Copyright 2023, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}"
rm -rf test/test-scan-build
meson setup test/test-scan-build -Dxwayland=true -Dman-pages=true --buildtype=release || RESULT=1
SCANBUILD="$(pwd)/test/testing-configurations/my-scan-build" ninja -C test/test-scan-build scan-build || RESULT=1
rm -rf test/test-scan-build

exit "${RESULT}"
