#!/bin/bash
# Copyright 2023 - 2024, project-repo and the cagebreak contributors
# SPDX-License-Identifier: MIT

RESULT=0

# shellcheck disable=2164
cd "${MESONCURRENTCONFIGDIR}/test"
# shellcheck disable=2046
shellcheck --source-path=../example_scripts/ $(ls -Itesting-configurations) || RESULT=1

cd "${MESONCURRENTCONFIGDIR}/example_scripts/" || RESULT=1
shellcheck ./* || RESULT=1

cd "${MESONCURRENTCONFIGDIR}/scripts/" || RESULT=1
shellcheck ./* || RESULT=1

exit "${RESULT}"
